################################################################################
## Calibration arguments
################################################################################

calibration-model=None
calibration-mode=marginalize
calibration-correction-type=None
spline-calibration-envelope-dict=None
spline-calibration-nodes=10
spline-calibration-curves=1000

################################################################################
## Data generation arguments
################################################################################

ignore-gwpy-data-quality-check=True
gps-tuple=None
gps-file=None
timeslide-file=None
timeslide-dict=None
trigger-time=1384782888.63
n-simulation=0
data-dict={'H1': 'gwf_files/H1.gwf', 'L1': 'gwf_files/L1.gwf'}
data-format=None
allow-tape=True
channel-dict={"H1": "injection", "L1": "injection"}
fetch-open-data-kwargs=None
frame-type-dict=None
data-find-url=None
data-find-urltype=osdf
gaussian-noise=False
zero-noise=False

################################################################################
## Detector arguments
################################################################################

detectors=[H1, L1]
duration=8.0
generation-seed=None
psd-dict={'H1': '/home/chun-lung.chan/dingo_lensing_team/tutorial_20260828/ex3_dingo_lensing_application/psds/H1_psd.txt', 'L1': '/home/chun-lung.chan/dingo_lensing_team/tutorial_20260828/ex3_dingo_lensing_application/psds/L1_psd.txt'}
asd-dataset=None
psd-fractional-overlap=0.5
post-trigger-duration=2.0
sampling-frequency=1024.0
psd-length=32
psd-maximum-duration=1024
psd-method=median
psd-start-time=None
maximum-frequency=448.0
minimum-frequency=20.0
tukey-roll-off=1.0
resampling-method=lal

################################################################################
## Injection arguments
################################################################################

injection=False
injection-dict=None
injection-file=None
injection-numbers=None
dingo-injection=False
injection-waveform-approximant=None
injection-frequency-domain-source-model=None
injection-waveform-arguments=None
injection-waveform-generator-constructor-dict=None
save-bilby-data-dump=False

################################################################################
## Job submission arguments
################################################################################

accounting=ligo.dev.o4.cbc.explore.test
accounting-user=None
label=label
local=True
local-generation=False
generation-pool=local-pool
local-plot=False
outdir=/home/kailibryan.doney/dingo_lensing_tutorial/materials/ex3_dingo_lensing_application/dingo_EXP1_lensed
overwrite-outdir=False
request-disk=5
request-memory-generation=16.0
request-memory=32.0
request-cpus=32
request-memory-importance-sampling=8.0
request-cpus-importance-sampling=32
conda-env=/home/chun-lung.chan/.conda/envs/dingo_lensing_team_20260826
sampling-requirements=None
extra-lines=None
simple-submission=False
scheduler=condor
scheduler-args=None
scheduler-module=None
scheduler-env=None
scheduler-analysis-time=7-00:00:00
submit=False
condor-job-priority=0
transfer-files=True
environment-variables=None
getenv=None
additional-transfer-paths=None
disable-hdf5-locking=False
log-directory=None
osg=False
gpu-desired-sites=None
cpu-desired-sites=None
generation-desired-sites=None
analysis-executable=None
analysis-executable-parser=None
scitoken-issuer=None
container=None

################################################################################
## Likelihood arguments
################################################################################

time-reference=geocent

################################################################################
## Output arguments
################################################################################

plot-data=False
plot-injection=False
plot-spectrogram=False
plot-corner=True
plot-weights=False
plot-log-probs=False
plot-pp=False
create-summary=False
email=None
notification=Never
queue=None
existing-dir=None
webdir=None
summarypages-arguments=None
result-format=hdf5
final-result=True
final-result-nsamples=20000

################################################################################
## Prior arguments
################################################################################

default-prior=BBHPriorDict
deltaT=0.2
Toffset=0.0
prior-dict-updates=None
prior-file=None
prior-dict={mass_1:Constraint(minimum=1.0, maximum=1001.0, name=None, latex_label=None, unit=None), mass_2:Constraint(minimum=1.0, maximum=1001.0, name=None, latex_label=None, unit=None), chirp_mass:bilby.gw.prior.UniformInComponentsChirpMass(minimum=10.0, maximum=180.0, name='chirp_mass', latex_label='$\\mathcal{M}$', unit=None, boundary=None), mass_ratio:bilby.gw.prior.UniformInComponentsMassRatio(minimum=0.125, maximum=1.0, name='mass_ratio', latex_label='$q$', unit=None, boundary=None, equal_mass=False), phase:Uniform(minimum=0.0, maximum=6.283185307179586, name='phase', latex_label='$\\phi$', unit=None, boundary='periodic'), a_1:Uniform(minimum=0.0, maximum=0.99, name=None, latex_label=None, unit=None, boundary=None), a_2:Uniform(minimum=0.0, maximum=0.99, name=None, latex_label=None, unit=None, boundary=None), tilt_1:Sine(minimum=0.0, maximum=3.141592653589793, name='tilt_1', latex_label='$\\theta_1$', unit=None, boundary=None), tilt_2:Sine(minimum=0.0, maximum=3.141592653589793, name='tilt_2', latex_label='$\\theta_2$', unit=None, boundary=None), phi_12:Uniform(minimum=0.0, maximum=6.283185307179586, name='phi_12', latex_label='$\\Delta\\phi$', unit=None, boundary='periodic'), phi_jl:Uniform(minimum=0.0, maximum=6.283185307179586, name='phi_jl', latex_label='$\\phi_{JL}$', unit=None, boundary='periodic'), theta_jn:Sine(minimum=0.0, maximum=3.141592653589793, name='theta_jn', latex_label='$\\theta_{JN}$', unit=None, boundary=None), luminosity_distance:Uniform(minimum=500.0, maximum=10000.0, name=None, latex_label=None, unit=None, boundary=None), lensing_delta_t:Uniform(minimum=0.0, maximum=0.1, name=None, latex_label=None, unit=None, boundary=None), mu_rel:Uniform(minimum=0.0, maximum=1.0, name=None, latex_label=None, unit=None, boundary=None), dec:Cosine(minimum=-1.5707963267948966, maximum=1.5707963267948966, name='dec', latex_label='$\\mathrm{DEC}$', unit=None, boundary=None), ra:Uniform(minimum=0.0, maximum=6.283185307179586, name='ra', latex_label='$\\mathrm{RA}$', unit=None, boundary='periodic'), psi:Uniform(minimum=0.0, maximum=3.141592653589793, name='psi', latex_label='$\\psi$', unit=None, boundary='periodic')}
enforce-signal-duration=True

################################################################################
## Waveform arguments
################################################################################

reference-frequency=20.0
waveform-approximant=IMRPhenomXPHM
catch-waveform-errors=True
numerical-relativity-file=None

################################################################################
## Sampler arguments
################################################################################

model=/home/chun-lung.chan/dingo_lensing_team/tutorial_20260828/ex3_dingo_lensing_application/models/model_lensed.pt
model-init=None
model-reference-time=1384782888.63
recover-log-prob=False
device=cpu
num-gnpe-iterations=30
num-samples=50000
batch-size=5000
density-recovery-settings=ProxyRecoveryDefault
importance-sample=True
importance-sampling-settings=Default
importance-sampling-updates={}
n-parallel=1

