#!/usr/bin/env python3
"""Turn dingo_env's package list into the container's pinned pip requirements.

The image should run exactly the software our tests run in dingo_env, except
with CPU builds of PyTorch. So every package keeps the version recorded in
dingo_env_pip_list.txt, apart from:

* The CUDA-only packages (nvidia-*, cuda-*, triton), which a CPU build of
  PyTorch does not use.
* torch and torchvision, pinned to the same versions but as "+cpu" builds from
  PyTorch's CPU index.
* dingo_lensing and modwaveforms, which the image installs from exact git
  commits instead (see dingo-lensing.def).

Standard library only.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List

CPU_INDEX = "https://download.pytorch.org/whl/cpu"
CUDA_ONLY = re.compile(r"^(nvidia-.*|cuda-.*|triton)$")
CPU_BUILDS = ("torch", "torchvision")
INSTALLED_FROM_GIT = ("dingo-lensing", "modwaveforms")
HEADER = "# Generated by make_requirements.py from dingo_env_pip_list.txt; do not edit."


def normalise(name: str) -> str:
    """Normalise a package name as pip does, so dingo_lensing == dingo-lensing."""
    return re.sub(r"[-_.]+", "-", name).lower()


def read_pip_list(path) -> Dict[str, str]:
    """Read `pip list --format=freeze` output into {normalised name: version}."""
    packages = {}
    for number, line in enumerate(Path(path).read_text().splitlines(), start=1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, separator, version = line.partition("==")
        if not separator or not version.strip():
            raise ValueError(f"{path}:{number}: Expected 'name==version', got {line!r}")
        key = normalise(name)
        if key in packages:
            raise ValueError(f"{path}:{number}: Duplicate package {name!r}")
        packages[key] = version.strip()
    return packages


def make_requirements(packages: Dict[str, str]) -> List[str]:
    """The requirements file's lines, sorted so the output is deterministic."""
    lines = [HEADER, f"--extra-index-url {CPU_INDEX}"]
    for name in sorted(packages):
        if CUDA_ONLY.match(name) or name in INSTALLED_FROM_GIT:
            continue
        version = packages[name]
        if name in CPU_BUILDS:
            version = version.split("+", 1)[0] + "+cpu"
        lines.append(f"{name}=={version}")
    return lines


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("pip_list", type=Path, help="dingo_env_pip_list.txt")
    output = parser.add_mutually_exclusive_group(required=True)
    output.add_argument("--output", type=Path, help="Write the requirements here.")
    output.add_argument(
        "--check", type=Path, help="Exit with an error unless this file is up to date."
    )
    args = parser.parse_args(argv)

    text = "\n".join(make_requirements(read_pip_list(args.pip_list))) + "\n"
    if args.output is not None:
        # Unix line endings everywhere, so the file is identical on every machine.
        with open(args.output, "w", newline="\n") as handle:
            handle.write(text)
    elif args.check.read_text().splitlines() != text.splitlines():
        sys.exit(f"{args.check} is out of date: Rerun make_requirements.py --output")


if __name__ == "__main__":
    main()
